// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oagoqvappwbzmkhsgtto.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9hZ29xdmFwcHdiem1raHNndHRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzMDA3NTAsImV4cCI6MjA2Njg3Njc1MH0.vlmDLDdXuZfCEd7MNv9H-YxHpquwYA2c3XrJxPrQwXw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});